export const STOCK_DETAIL_REQUESTING = 'STOCK_DETAIL_REQUESTING';
export const STOCK_DETAIL_REQUEST_SUCCESS = 'STOCK_DETAIL_REQUEST_SUCCESS';
export const STOCK_DETAIL_REQUEST_ERROR = 'STOCK_DETAIL_REQUEST_ERROR';

export const STOCK_MANAGEMENT_REQUESTING = 'STOCK_MANAGEMENT_REQUESTING';
export const STOCK_MANAGEMENT_REQUEST_SUCCESS = 'STOCK_MANAGEMENT_REQUEST_SUCCESS';
export const STOCK_MANAGEMENT_REQUEST_ERROR = 'STOCK_MANAGEMENT_REQUEST_ERROR';

export const COMPANY_INFO_REQUESTING = 'COMPANY_INFO_REQUESTING';
export const COMPANY_INFO_REQUEST_ERROR = 'COMPANY_INFO_REQUEST_ERROR';
export const COMPANY_INFO_REQUEST_SUCCESS = 'COMPANY_INFO_REQUEST_SUCCESS';

export const ASSOCIATE_REQUESTING = 'ASSOCIATE_REQUESTING';
export const ASSOCIATE_REQUEST_SUCCESS = 'ASSOCIATE_REQUEST_SUCCESS';
export const ASSOCIATE_REQUEST_ERROR = 'ASSOCIATE_REQUEST_ERROR';

export const KQKD_REQUESTING = 'KQKD_REQUESTING';
export const KQKD_REQUEST_SUCCESS = 'KQKD_REQUEST_SUCCESS';
export const KQKD_REQUEST_ERROR = 'KQKD_REQUEST_ERROR';

export const CDKT_REQUESTING = 'CDKT_REQUESTING';
export const CDKT_REQUEST_SUCCESS = 'CDKT_REQUEST_SUCCESS';
export const CDKT_REQUEST_ERROR = 'CDKT_REQUEST_ERROR';

export const STOCK_NEWS_REQUESTING = 'STOCK_NEWS_REQUESTING';
export const STOCK_NEWS_REQUEST_SUCCESS = 'STOCK_NEWS_REQUEST_SUCCESS';
export const STOCK_NEWS_REQUEST_ERROR = 'STOCK_NEWS_REQUEST_ERROR';

export const STOCK_EVENTS_REQUESTING = 'STOCK_EVENTS_REQUESTING';
export const STOCK_EVENTS_REQUEST_SUCCESS = 'STOCK_EVENTS_REQUEST_SUCCESS';
export const STOCK_EVENTS_REQUEST_ERROR = 'STOCK_EVENTS_REQUEST_ERROR';