export const CATEGORY_SET = 'CATEGORY_SET';
export const CATEGORY_UNSET = 'CATEGORY_UNSET';

export const SETTING_SET = 'SETTING_SET';
export const SETTING_UNSET = 'SETTING_UNSET';

export const SYMBOL_ACTIVE_SET = 'SYMBOL_ACTIVE_SET';
export const SYMBOL_ACTIVE_UNSET = 'SYMBOL_ACTIVE_UNSET';

export const SYMBOL_ADD = 'SYMBOL_ADD';
export const SYMBOL_SCROLL = 'SYMBOL_SCROLL';