export const INDEX_REQUESTING = 'INDEX_REQUESTING';
export const INDEX_REQUEST_SUCCESS = 'INDEX_REQUEST_SUCCESS';
export const INDEX_REQUEST_ERROR = 'INDEX_REQUEST_ERROR';

export const WORLD_INDEX_REQUESTING = 'WORLD_INDEX_REQUESTING';
export const WORLD_INDEX_REQUEST_SUCCESS = 'WORLD_INDEX_REQUEST_SUCCESS';
export const WORLD_INDEX_REQUEST_ERROR = 'WORLD_INDEX_REQUEST_ERROR';