export const INDEX_REQUESTING = 'INDEX_REQUESTING';
export const INDEX_REQUEST_SUCCESS = 'INDEX_REQUEST_SUCCESS';
export const INDEX_REQUEST_ERROR = 'INDEX_REQUEST_ERROR';

export const WORLD_INDEX_REQUESTING = 'WORLD_INDEX_REQUESTING';
export const WORLD_INDEX_REQUEST_SUCCESS = 'WORLD_INDEX_REQUEST_SUCCESS';
export const WORLD_INDEX_REQUEST_ERROR = 'WORLD_INDEX_REQUEST_ERROR';

export const ALL_STOCK_REQUESTING = 'ALL_STOCK_REQUESTING';
export const ALL_STOCK_REQUEST_SUCCESS = 'ALL_STOCK_REQUEST_SUCCESS';
export const ALL_STOCK_REQUEST_ERROR = 'ALL_STOCK_REQUEST_ERROR';

export const GET_STOCK_BY_ID_REQUESTING = 'GET_STOCK_BY_ID_REQUEST';
export const GET_STOCK_BY_ID_REQUEST_SUCCESS = 'GET_STOCK_BY_ID_REQUEST_SUCCESS';
export const GET_STOCK_BY_ID_REQUEST_ERROR = 'GET_STOCK_BY_ID_REQUEST_ERROR';

export const CLEAR_PART_REQUEST = 'CLEAR_PART_REQUEST';

export const TOP_CHANGE_BY_ID_REQUESTING = 'TOP_CHANGE_BY_ID_REQUESTING';
export const TOP_CHANGE_BY_ID_REQUEST_SUCCESS = 'TOP_CHANGE_BY_ID_REQUEST_SUCCESS';
export const TOP_CHANGE_BY_ID_REQUEST_ERROR = 'TOP_CHANGE_BY_ID_REQUEST_ERROR';
