export const TOP_INTEREST_REQUESTING = 'TOP_INTEREST_REQUESTING';
export const TOP_INTEREST_REQUEST_SUCCESS = 'TOP_INTEREST_REQUEST_SUCCESS';
export const TOP_INTEREST_REQUEST_ERROR = 'TOP_INTEREST_REQUEST_ERROR';
